version: '3.7'

services:
  front-end:
    image: node:12
    volumes:
      - ./:/app
      - /app/node_modules/
    working_dir: /app
    command: bash -c 'npm install react-scripts@3.4.1 -g && npm i && npm run front-end'
    ports:
      - "3000:3000"
    stdin_open: true

  back-end:
    image: node:12
    volumes:
      - ./:/app
      - /app/node_modules/
    working_dir: /app
    command: bash -c 'npm i && npm run back-end'
    ports:
      - "4000:4000"

  mongodb-container:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: homeserve
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: randomPassword
    ports:
      - 27017:27017
    volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
